@startuml
'https://plantuml.com/class-diagram

class Word {
    + position_in_text: int
    + lexeme: str
    + basis: str
    + part_of_speech: str
    + ending: str
    + case: str
    + gender: str
    + number: str
    + Word(position_in_text, lexeme, basis, part_of_speech, ending, case, gender, number)
}

class GeneralController {
    - main_window: MainWindow
    - file_controller: FileController
    - format_controller: FormatController
    - morphology_controller: MorphologyController
    - word_form_generation_controller: WordFormGenerationController
    + GeneralController()
    + list[Word] word_list_generation()
}

class FileController {
    - file_name: str
    + FileController(file_name: str)
    + str file_format_definition()
}

abstract class FormatController {
    - file_name: str
    + FormatController(file_name: str)
    + list[str] file_parse()
}

class DOCController {
    - file_name: str
    + DOCController(file_name: str)
    + list[str] file_parse()
}

class DOCXController {
    - file_name: str
    + DOCXController(file_name: str)
    + list[str] file_parse()
}

class MorphologyController {
    - word_list: list[str]
    + MorphologyController(word_list: list[str])
    - void word_list_sort()
    + list[Word] word_objects_creation()
}

class SaveController {
    - save_path: str
    + SaveController(save_path: str)
    - file form_file(list[Word])
    + void save_file()
}

class WordFormGenerationController {
    - word_form: str
    - basis: str
    - number: str
    + WordFormGenerationController(word_form: str, basis: str, number: str)
    + str word_form_generation()
}

class MainWindow {

}

class AboutProgramWindow {
    
}

class WordFormGenerationWindow {

}

GeneralController ---> Word
GeneralController ---* FileController
GeneralController ---* FormatController
GeneralController ---* MorphologyController
GeneralController ---* SaveController
GeneralController ---* WordFormGenerationController

FormatController ---|> DOCController
FormatController ---|> DOCXController

MorphologyController ---> Word

SaveController ---> Word

WordFormGenerationController ---> Word

@enduml